---
    - name: 1. Install epel-release and borgbackup to VM
      hosts: all
      
      tasks:
        - name: Install epel-release
          become: true
          yum: name=epel-release

        - name: Install borgbackup
          become: true
          yum: name=borgbackup update_cache=yes state=latest

    - name: 2. Configure borg client VM
      hosts: borgclient
      become: true
      become_user: root

      tasks:
        - name: Generate ssh_key for root
          user:
            name: root
            generate_ssh_key: yes
            ssh_key_bits: "2048"
            ssh_key_file: ".ssh/id_rsa"

        - name: Download ssh-key to host machine
          fetch:
            src: /root/.ssh/id_rsa.pub
            dest: tmp/id_rsa.tmp
            flat: yes

        - name: Rename ssh-key on host machine
          become: false
          local_action: shell cat tmp/id_rsa.tmp >> tmp/authorized_keys

    - name: 3. Configuration borg server VM
      hosts: borgserver
      become: true
      vars:
        repository_path: /root/backup_repository

      tasks:
        - name: Create borg repository
#          become: true
          become_user: root
          command: borg init -e repokey "{{ repository_path }}"
          environment:
            BORG_PASSPHRASE: testingborg

        - name: Deploy SSH key from host machine
          authorized_key:
            user: root
            state: present
            key: "{{ lookup('file', 'tmp/authorized_keys') }}"

    - name: 4. Creating first backup on borg client VM
      hosts: borgclient
      vars:
        borgserver_address: "192.168.110.101"
        borg_user: root
        repository_path: /root/backup_repository
        
      tasks:
        - name: Create first backup
#          become_user: root
          become: true
          command: "borg create --compression lzma,2 \"{{ borg_user }}\"@\"{{ borgserver_address }}\":\"{{ repository_path }}\"::\"etc_backup-{now:%Y-%m-%d_%H:%M:%S}\" /etc"
          environment:
            BORG_PASSPHRASE: testingborg
          tags:
            - run_backup
    
        - name: Copy sh script
          become_user: "{{ borg_user }}"
          become: true
          copy:
            src: files/backup.sh
            dest: /root/backup.sh
            owner: root
            group: root
            mode: '0700'
            follow: yes
          tags:
            - sh

        - name: Create cron job
          become: true
          cron:
            name: "backup_etc"
            minute: "*/10"
            job: "/root/backup.sh >/dev/null 2>&1"
          tags:
            - cron
...