MACHINES = {
  :borgserver => {
        :box_name => "centos/7",
        :ip_addr => '192.168.110.101',
  },
  :borgclient => {
        :box_name => "centos/7",
        :ip_addr => '192.168.110.102',
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|
          box.vm.box_check_update = false
          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
          box.ssh.insert_key = false
          box.vm.network "private_network", ip: boxconfig[:ip_addr]
          box.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "256", "--cpus", "2"]
          vb.name = boxname.to_s
          end
      box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
      SHELL
      # case boxname.to_s
      # when "web"
      #   box.vm.network "forwarded_port", guest: 80, host: 8080
      #   box.vm.network "forwarded_port", guest: 443, host: 8443
      # config.vm.provision "ansible" do |ansible|
      #   ansible.verbose = "v"
      #   ansible.playbook = "playbook.yml"
      #   end 
      #  end
       end
   end
end