---
- name: Preparatory work
  hosts: all
  become: True
  gather_facts: False
  roles:
    - role: preparation

- name: Setup tun server openvpn
  hosts: server
  become: True
  gather_facts: False
  roles:
    - role: tun-server

- name: Setup tun client openvpn
  hosts: client
  become: True
  gather_facts: False
  roles:
    - role: tun-client
...