---
  - name: Copy Quagaa and Zebra configs to router1
    copy:
      src: ospfd_router1.conf
      dest: /etc/quagga/ospfd.conf
    notify: restart quagga

    when: ansible_hostname == "router1"

  - name: Copy Quagaa and Zebra configs to router3
    copy:
      src: ospfd_router3.conf
      dest: /etc/quagga/ospfd.conf
    notify: restart quagga

    when: ansible_hostname == "router3"

  - name: Change ospfd.conf ownership, group
    file:
      path: /etc/quagga/ospfd.conf
      owner: quagga
      group: quagga
...