---
  ipa_server_ip: 192.168.11.150
  ipa_client_ip: 192.168.11.151
  ipa_server_hostname: ipaserver
  ipa_client_hostname: ipaclient
  domain_name: test.local
  realm_name: TEST.LOCAL
  ipa_user: admin
  ds_pass: 12345678
  admin_pass: 12345678 
...