Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    config.vm.define "rpm"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "2"
    end
    config.vm.hostname = "rpm"
    config.vm.network "private_network", ip: "192.168.111.111"
    config.vm.network "forwarded_port", guest: 80, host: 8080
#    config.vm.provision "shell", path: "script.sh"
end