---
  - name: Configure hostname IPA client
    hostname:
      name: "{{ ipa_client_hostname }}.{{ domain_name }}"
  
  - name: ipa-server configuration
    ignore_errors: Yes
    command: ipa-client-install -U --mkhomedir --realm {{ realm_name }} --domain {{ domain_name }} --server={{ ipa_server_hostname }}.{{ domain_name }} --principal=pushkin --password=12345678 
...
