---
- name: Preparatory work
  hosts: all
  become: True
  roles:
    - selinux
    - install
    - copykey

- name: Configure openvpn server
  hosts: server
  become: True

  roles:
    - tap-configuration
