# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:inetRouter => {
        :box_name => "centos/7",
        :net => [
#                {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                 {adapter: 2, auto_config: false, virtualbox__intnet: "router-net"},
                 {adapter: 3, auto_config: false, virtualbox__intnet: "router-net"},
                ]
  },
  :centralRouter => {
        :box_name => "centos/7",
        :net => [
 #               {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                {adapter: 2, auto_config: false, virtualbox__intnet: "router-net"},
                {adapter: 3, auto_config: false, virtualbox__intnet: "router-net"},
                {ip: '192.168.0.1', adapter: 4, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                {ip: '192.168.0.33', adapter: 5, netmask: "255.255.255.240", virtualbox__intnet: "hw-net"},
                {ip: '192.168.0.65', adapter: 6, netmask: "255.255.255.192", virtualbox__intnet: "wi-fi-net"},
                {ip: '192.168.255.5', adapter: 7, netmask: "255.255.255.252", virtualbox__intnet: "central-net1"},
                {ip: '192.168.255.9', adapter: 8, netmask: "255.255.255.252", virtualbox__intnet: "central-net2"}
                ]
  },
  
  :centralServer => {
        :box_name => "centos/7",
        :net => [
                {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                ]
  },

  :office1Router => {
    :box_name => "centos/7",
    :net => [
               {ip: '192.168.255.6', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "central-net1"},
               {ip: '192.168.2.1', adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "office1-dev-net"},
               {ip: '192.168.2.65', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "office1-test-servers-net"},
               {ip: '192.168.2.129', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "office1-managers-net"},
               {ip: '192.168.2.193', adapter: 6, netmask: "255.255.255.192", virtualbox__intnet: "office1-hardware-net"},
               {ip: '192.168.3.1', adapter: 7, netmask: "255.255.255.192", virtualbox__intnet: "test1-net"}
            ]
  },

  :office1Server => {
    :box_name => "centos/7",
    :net => [
               {ip: '192.168.2.66', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "office1-test-servers-net"},
            ]
  },

  :testClient1 => {
    :box_name => "centos/7",
    :net => [
               {ip: '192.168.3.2', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "test1-net"},
               {ip: '10.10.10.254', adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "testLAN"},
            ]
  },

  :testServer1 => {
    :box_name => "centos/7",
    :net => [
               {ip: '192.168.3.3', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "test1-net"},
               {ip: '10.10.10.1', adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "testLAN"},
            ]
  },

  :testClient2 => {
    :box_name => "centos/7",
    :net => [
               {ip: '192.168.3.4', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "test1-net"},
               {ip: '10.10.10.254', adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "testLAN"},
            ]
  },

  :testServer2 => {
    :box_name => "centos/7",
    :net => [
               {ip: '192.168.3.5', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "test1-net"},
               {ip: '10.10.10.1', adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "testLAN"},
            ]
  },

  :office2Router => {
    :box_name => "centos/7",
    :net => [
               {ip: '192.168.255.10', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "central-net2"},
               {ip: '192.168.1.1', adapter: 3, netmask: "255.255.255.128", virtualbox__intnet: "office2-dev-net"},
               {ip: '192.168.1.129', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "office2-test-servers-net"},
               {ip: '192.168.2.193', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "office2-hardware-net"},
            ]
  },

  :office2Server => {
    :box_name => "centos/7",
    :net => [
               {ip: '192.168.1.130', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "office2-test-servers-net"},
            ]
  }

}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s
        box.vm.box_check_update = false
        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
      end
    end
  end
