---
- name: Install openvpn
  package:
    name: epel-release
    state: present

- name: Install openvpn and iperf3
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - openvpn
    - iperf3
  notify: Enable openvpn service
...