---
  - name: Copy postgresql.conf config
    copy:
      src: files/postgresql.conf
      dest: /var/lib/pgsql/11/data/postgresql.conf
      owner: postgres
      group: postgres
      mode: '0600'
      force: Yes

  - name: Restart PostgreSQL
    service:
      name: postgresql-11
      state: restarted
    
  - name: Copy from template pg_hba
    template:
      src: templates/pg_hba.conf.j2
      dest: /var/lib/pgsql/11/data/pg_hba.conf
      owner: postgres
      group: postgres
      mode: '0600'
      force: Yes
    
  - name: Reload PostgreSQL
    service:
      name: postgresql-11
      state: reloaded
...
