---
  - name: Configuration inetRouter
    hosts: inetRouter
    become: true

    tasks:
      - name: Set ip forwarding on in /proc and verify token value with the sysctl command
        sysctl:
          name: net.ipv4.ip_forward
          value: '1'
          sysctl_set: yes

      - name: IPtables Configuration
        command: iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
      
      - name: ip routing 192.168.0.0/24
        command: ip route add 192.168.0.0/24 via 192.168.255.2

      - name: ip routing 192.168.1.0/24
        command: ip route add 192.168.1.0/24 via 192.168.255.2
      
      - name: ip routing 192.168.2.0/24
        command: ip route add 192.168.2.0/24 via 192.168.255.2

      - name: ip routing 192.168.255.4/30
        command: ip route add 192.168.255.4/30 via 192.168.255.2

      - name: ip routing 192.168.255.8/30
        command: ip route add 192.168.255.8/30 via 192.168.255.2

  - name: Configuration centralRouter
    hosts: centralRouter
    become: true

    tasks:
      - name: Set DEFROUTE=No
        shell: echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
      
      - name: Change default gateway
        shell: echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
    
      - name: Set ip forwarding on in /proc and verify token value with the sysctl command
        sysctl:
          name: net.ipv4.ip_forward
          value: '1'
          sysctl_set: yes

      - name: ip routing 192.168.2.0/24
        command: ip route add 192.168.2.0/24 via 192.168.255.6
      
      - name: ip routing 192.168.1.0/24
        command: ip route add 192.168.1.0/24 via 192.168.255.10

  - name: Configuration centralServer
    hosts: centralServer
    become: true

    tasks:
      - name: Set DEFROUTE=No
        shell: echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
      
      - name: Change default gateway
        shell: echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1

      - name: Restart network
        systemd:
          name: network
          state: reloaded

  - name: Configuration office1Router
    hosts: office1Router
    become: true

    tasks:
      - name: Set DEFROUTE=No
        shell: echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
      
      - name: Change default gateway
        shell: echo "GATEWAY=192.168.255.5" >> /etc/sysconfig/network-scripts/ifcfg-eth1
    
      - name: Set ip forwarding on in /proc and verify token value with the sysctl command
        sysctl:
          name: net.ipv4.ip_forward
          value: '1'
          sysctl_set: yes
      
      - name: Restart network
        service: 
          name: network
          state: restarted

  - name: Configuration office1Server
    hosts: office1Server
    become: true

    tasks:
      - name: Set DEFROUTE=No
        shell: echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
      
      - name: Change default gateway
        shell: echo "GATEWAY=192.168.2.65" >> /etc/sysconfig/network-scripts/ifcfg-eth1

      - name: Restart network
        command: systemctl restart network
    
      # - name: Restart network
      #   systemd:
      #     name: network
      #     state: reloaded
    
  - name: Configuration office2Router
    hosts: office2Router
    become: true

    tasks:
      - name: Set DEFROUTE=No
        shell: echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
      
      - name: Change default gateway
        shell: echo "GATEWAY=192.168.255.9" >> /etc/sysconfig/network-scripts/ifcfg-eth1
    
      - name: Set ip forwarding on in /proc and verify token value with the sysctl command
        sysctl:
          name: net.ipv4.ip_forward
          value: '1'
          sysctl_set: yes
      
      # - name: Restart network
      #   systemd:
      #     name: network
      #     state: reloaded

      - name: Restart network
        command: systemctl restart network

  - name: Configuration office1Server
    hosts: office2Server
    become: true

    tasks:
      - name: Set DEFROUTE=No
        shell: echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
      
      - name: Change default gateway
        shell: echo "GATEWAY=192.168.1.129" >> /etc/sysconfig/network-scripts/ifcfg-eth1

      - name: Restart network
        command: systemctl restart network
        
      # - name: Restart network
      #   systemd:
      #     name: network
      #     state: reloaded

...

