---
- name: Copy ovpn key from host to guest machines
  hosts: all
  become: True
  
  copy:
    src: files/static.key
    dest: /etc/openvpn/static.key
    owner: root
    group: root
    mode: '0600'
...