---
  - name: Install nfs-utils
    package:
      name: nfs-utils
      state: present

  - name: Start and enable nfs
    service:
      name: nfs-server
      state: started
      enabled: yes
...
    