version: "3.7"
services:

    MongoDB:
        container_name: mongo
        image: mongo:3
        networks: 
            - graylog_stack
    
    elasticsearch:
        container_name: elastic
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.2
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - http.host=0.0.0.0
            - transport.host=localhost
            - network.host=0.0.0.0
        ulimits:
            memlock:
                soft: -1
                hard: -1
        deploy:
            resources:
                limits:
                    memory: 1g
        ports:
            - 9200:9200
        networks:
            - graylog_stack
    
    graylog:
        container_name: graylog
        image: graylog/graylog:3.1
        environment:
#            - GRAYLOG_PASSWORD_SECRET=7Ovj0f2uEVOlTNJoo7ZfsFpUGyL9BouVpz5vlYVfHigtRYUWE8nr30j6ubWBywrOKdkYQzzeVd7dwjNB7948MxVe9tB2eXBr
            - GRAYLOG_ROOT_PASSWORD_SHA2=07af4c7781252bd82444f65072d80a017ca5458da0d6d4785447b2525712c2b1
            - GRAYLOG_HTTP_EXTERNAL_URI=http://84.201.158.85:9000/
            - GRAYLOG_HTTP_PUBLISH_URI=http://84.201.158.85:9000/
        networks:
            - graylog_stack
        depends_on:
            - MongoDB
            - elasticsearch
        ports:
            # Graylog web interface and REST API
            - 9000:9000
            # Syslog TCP
            - 1514:1514
            # Syslog UDP
            - 1514:1514/udp
            # GELF TCP
            - 12201:12201
            # GELF UDP
            - 12201:12201/udp
networks:
    graylog_stack:
        driver: bridge
