---
- name: Copy percona configuration
  copy:
    src: "{{ item }}"
    dest: "/etc/my.cnf.d/"
  with_fileglob:
    - files/etc/my.cnf.d/*

- name: Restart MySQL
  service:
    name: mysql
    state: restarted

- name: Copy database dump file
  copy:
    src: etc/bet.dmp
    dest: /tmp/bet.dmp

- name: Restore database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_password }}"
    name: bet
    state: import
    target: /tmp/bet.dmp

- name: create replication user
  command: >
    mysql
      -uroot
      -p'{{ mysql_password }}'
      -e 'CREATE USER "{{ replica_user }}" IDENTIFIED BY "{{ replica_password }}"'

- name: Priv to replication user
  command: >
    mysql
      -uroot
      -p'{{ mysql_password }}'
      -e 'GRANT REPLICATION SLAVE ON *.* TO "{{ replica_user }}"@"%" IDENTIFIED BY "{{ replica_password }}";'

- name: Save MySQL dump
  shell: |
    mysqldump > /tmp/dump.sql \
      -uroot \
      -p'{{ mysql_password }}' \
      --ignore-table=bet.events_on_demand \
      --ignore-table=bet.v_same_event \
      --all-databases \
      --triggers \
      --routines \
      --master-data
  ignore_errors: yes 

- name: Get dump from master to host machine
  fetch:
    src: /tmp/dump.sql
    dest: dump.sql
    flat: yes
...