---
- name: Job with centralServer
  hosts: centralServer
  become: True
  tasks:

    - name: Add epel-release repo
      package:
        name: epel-release
        state: present

    - name: Install nginx
      package:
        name: nginx
        state: present

    - name: restart nginx
      service:
        name: nginx
        state: restarted

    - name: Config centralServer
      command: "{{ item }}"
      ignore_errors: yes
      with_items:
        - ip route del default
        - ip route add default via 192.168.10.1 dev eth1

- name: Routers config
  hosts: routers
  become: True
  tasks:
    - name: Enable ipv4 forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes

    - name: Restart network
      service:
        name: network
        state: restarted

- name: Config inetRouter
  hosts: inetRouter
  become: True

  tasks:
    - name: addressing and routing
      command: "{{item}}"
      with_items:
        - iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
        - ip route add 192.168.10.0/24 via 192.168.255.3 dev eth1

    - name: Copy iptables
      copy:
        force: yes
        src: files/iptables.rules
        dest: /tmp/iptables.rules

    - name: Restore iptables.rules
      shell: iptables-restore < /tmp/iptables.rules

    - name: Edit sshd config
      shell: sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config

    - name: Restart sshd
      service:
        name: sshd
        state: restarted

- name: Config inetRouter2
  hosts: inetRouter2
  become: True
  tasks:

   - name: Routing
     command: "{{ item }}"
     with_items:
      - ip route del default
      - ip route add default via 192.168.255.1 dev eth1
      - ip route add 192.168.10.0/24 via 192.168.255.3 dev eth1
      - iptables -A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
      - iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
      - iptables -t nat  -A PREROUTING -s 10.0.2.2 -d 10.0.2.15 -p tcp -m tcp --dport 80 -j DNAT --to-destination 192.168.10.2:80
      - iptables -t nat  -A POSTROUTING -d 192.168.10.2 -p tcp -m tcp --dport 80 -j SNAT --to-source 192.168.255.2
      - iptables -A  FORWARD -j ACCEPT

- name: config centralRouter
  hosts: centralRouter
  become: True
  tasks:

    - name: Routing
      command: "{{ item }}"
      ignore_errors: yes
      with_items:
        - ip route del default
        - ip route add default via 192.168.255.1 dev eth1

    - name: Copy knocking script
      copy:
        force: yes
        src: files/knock.sh
        dest: /usr/bin/knock.sh
        mode: +x
        
    - name: Install nmap
      yum:
        name: nmap
        state: present
...
   