---
    - name: Install and configure NGINX
      hosts: all
      become: true
      vars:
        nginx_listen_port: 8080
    
      tasks:
        - name: Install EPEL Repo package from standart repo
          yum:
            name: epel-release
            state: present
          tags:
            - epel-package
            - packages
    
        - name: Install nginx package from EPEL Repo
          yum:
            name: nginx
            state: latest
          notify:
            - restart nginx
          tags:
            - nginx-package
            - packages
          
        - name: Copy configuration file
          template: 
            src: files/nginx.conf.j2
            dest: /etc/nginx/nginx.conf
          notify:
            - reload nginx
          tags:
            - nginx_configuration
        
        - name: Start nginx service
          service:
            name: nginx
            state: started


      handlers:
        - name: restart nginx
          systemd:
            name: nginx
            state: restarted
            enabled: yes
      
        - name: reload nginx
          systemd:
            name: nginx
            state: reloaded
...