---
  - name: Configure hostname IPA Server
    hostname:
      name: "{{ ipa_server_hostname }}.{{ domain_name }}"

  - name: Copy jinja2 hosts template
    template:
      src: templates/hosts.j2
      dest: /etc/hosts
      force: Yes

  - name: ipa-server configuration
    ignore_errors: Yes
    command: ipa-server-install --unattended --realm {{ realm_name }} --domain {{ domain_name }} --ds-password={{ ds_pass }} --admin-password={{ admin_pass }} --hostname={{ ipa_server_hostname }}.{{ domain_name }} --ip-address={{ ipa_server_ip }} --setup-dns --auto-forwarders --no-reverse
...
