---
  - name: Install PostgreSQL Yum Repository
    yum:
      name:  https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
      state: present

  - name: Install PostgreSQL packages
    package:
      name: "{{ postgresql_packages }}"
      state: present
    notify: PostgreSQL service enable
    
...