---
- name: Install and configure mail
  hosts: mail
  become: true
  tasks:
    - name: Add records to /etc/hosts
      lineinfile:
        path: /etc/hosts
        state: present
        line: |
          192.168.1.20 mail.otus.local
          192.168.1.20 otus.local 
         
    - name: install postfix dovecot
      yum:
        name: 
        - postfix
        - dovecot
        - telnet
        state: present
  
    - name: Copy main.cf
      copy:
        src: main.cf
        dest: /etc/postfix/main.cf
    
    - name: ensure Postfix is started and runs at startup
      service:
        name: postfix
        state: restarted
        enabled: yes  
   
    - name: create vmail group
      group:
        name: vmail
        gid: 5000

    - name: create vmail user
      user:
        name: vmail
        group: vmail
        uid: 5000
        home: /var/mail

    - name: set secure permissions and ownership on /etc/dovecot
      file:
        path: /etc/dovecot
        state: directory
        owner: vmail
        group: dovecot
        mode: o-rwx

    - name: create /var/mail/vhosts
      file:
        path: /var/mail/vhosts
        state: directory
        owner: vmail
        group: vmail

    - name: ensure Dovecot is started and runs at startup
      service:
        name: dovecot
        state: started
        enabled: yes
...