# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/8"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end
 
  config.vm.define "dynamic" do |dynamic|
    dynamic.vm.network "private_network", ip: "192.168.100.10"
    dynamic.vm.hostname = "dynamic"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "vv"
    ansible.playbook = "provision.yml"
    ansible.become = "true"
  end

end