---
- name: Patroni | configure | Configure patroni systemd service file
  template:
    src: patroni.service.j2
    dest: /etc/systemd/system/patroni.service

- name: Patroni | configure | Create patroni directories
  file:
    path: "{{ item }}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0700
  with_items:
      - /var/data/base
      - /etc/patroni/
  tags:
    - dirs

- name: Patroni | configure | Copy patroni config file
  template:
    src: patroni.yml.j2
    dest: /etc/patroni/patroni.yml

- name: Patroni | configure | Start patroni cluster
  systemd:
    name: patroni
    state: restarted
    daemon_reload: True
    enabled: true
