---
- name: Patroni | install | Install patroni requiered packages
  apt:
    name: "{{ apt_packages }}"
    update_cache: True
    state: present

- name: Patroni | install | Add postgresql-11 repo key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Patroni | install | Add postgresql-11 repo
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main
    state: present


- name: Patroni | install | Install postgresql-11
  apt:
    name: postgresql-11
    state: present
    update_cache: True

- name: Stop postgresql service
  systemd:
    name: postgresql
    state: stopped
    enabled: no

- name: Patroni | install | Upgrade pip
  pip: 
    name: pip
    state: forcereinstall

- name: Patroni | install | Install pip packages
  pip:
    name: "{{ pip_packages }}"
    state: present
  tags:
    - pip

- name: Patroni | install | Install patroni
  pip:
    name: patroni
    state: present
  tags:
    - pip-patroni
