---
  - name: Patroni | install | Install patroni requiered packages
    yum:
      name: "{{ install_packages }}"
      state: present

  - name: Stop postgresql service
    service:
      name: postgresql-11
      state: stopped
      enabled: Yes
    ignore_errors: Yes

  - name: Patroni | install | Upgrade pip
    pip: 
      name: pip
      state: forcereinstall
      executable: pip3.6

  - name: Patroni | install | Install pip packages
    pip:
      name: "{{ pip_packages }}"
      state: present
      executable: pip3.6

  - name: Patroni | install | Install patroni
    pip:
      name: patroni
      state: present
      executable: pip3.6
...
