---
- name: Install percona to master and slave
  hosts: all
  become: True
  gather_facts: True
  roles:
    - percona-install

- name: Config master server
  hosts: master
  become: True
  gather_facts: True
  roles:
    - master-config

- name: Config slave server
  hosts: slave
  become: True
  gather_facts: True
  roles:
    - slave-config
...