---
- name: AAA settings
  hosts: all
  become: True
  vars:
    password: $6$1u.A5K8ybqZLdHlt$wMuF1BcjWGHl0G05YOm2HZ8HZ9.JcEJFJnmpGMNsBu9Ih88RAeLK6Q56p/A2woGY5ns2tIPFdivnZ5JW0STXK0

  tasks:
    - name: Set timezone
      timezone:
        name: Europe/Moscow
        
    - name: Add user day
      user:
        name: day
        password: "{{ password }}"
 
    - name: Add user night
      user:
        name: night
        password: "{{ password }}"  
    
    - name: Add user friday
      user:
        name: friday
        password: "{{ password }}"

    - name: Add user admin
      user:
        name: admin
        password: "{{ password }}"
        
    - name: Copy time.conf for pam_time
      copy: 
        src: files/time.conf
        dest: /etc/security/
        owner: root
        group: root
        mode: '0644'
        follow: yes

    - name: Copy sshd config
      copy:
        src: files/sshd
        dest: /etc/pam.d/
        owner: root
        group: root
        mode: '0644'
        follow: yes
      
    # Некрасивое решение с предоставленим доступа к systemd пользователю day для возможности управления docker daemon      
    # - name: Copy polkit rule
    #   copy:
    #     src: files/01-systemd.rules
    #     dest: /etc/polkit-1/rules.d/
    #     owner: root
    #     group: root
    #     mode: '0644'
    #   notify: restart polkit
        
    - name : Update sshd config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication.*no'
        line: 'PasswordAuthentication yes'
      notify: restart sshd

    - name: Install required packages
      yum: name={{ item }} state=latest
      with_items:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2

    - name: Add docker repo
      shell: yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker
      yum: name={{ item }} state=latest
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: Add user add to docker group
      user:
        name: day
        groups: docker
        append: yes

    - name: Add day to sudoers to manage dockerd
      lineinfile:
        path: /etc/sudoers
        line: 'day ALL=(ALL) NOPASSWD: /bin/systemctl start docker.service, /bin/systemctl stop docker.service, /bin/systemctl restart docker.service'

  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted

    # Раскомментить если используется решение с PolKit
    # - name: restart polkit
    #   service:
    #     name: polkit
    #     state: restarted 
...